# Generated by Django 3.2.9 on 2022-02-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(max_length=50)),
                ('h2', models.CharField(max_length=50)),
                ('h4', models.CharField(max_length=50)),
                ('li', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='media/hero')),
            ],
        ),
    ]
