# Generated by Django 3.2.9 on 2022-03-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hero_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
                ('hero_h1', models.CharField(max_length=200)),
                ('hero_h2', models.CharField(max_length=200)),
                ('hero_table', models.CharField(max_length=200)),
                ('hero_item1', models.CharField(max_length=200)),
                ('hero_item2', models.CharField(max_length=200)),
                ('hero_item3', models.CharField(max_length=200)),
                ('hero_item4', models.CharField(max_length=200)),
                ('hero_item5', models.CharField(max_length=200)),
                ('hero_item6', models.CharField(max_length=200)),
                ('hero_item7', models.CharField(max_length=200)),
                ('hero_item8', models.CharField(max_length=200)),
                ('hero_item9', models.CharField(max_length=200)),
                ('hero_price', models.IntegerField()),
                ('hero_image', models.ImageField(upload_to='media/hero')),
                ('about_h1', models.CharField(max_length=200)),
                ('about_p', models.TextField()),
                ('about_p2', models.TextField()),
                ('about_h2', models.CharField(max_length=200)),
                ('table_title', models.CharField(max_length=200)),
                ('table_feature1', models.CharField(max_length=200)),
                ('table_feature2', models.CharField(max_length=200)),
                ('table_feature3', models.CharField(max_length=200)),
                ('table_feature4', models.CharField(max_length=200)),
                ('table_feature5', models.CharField(max_length=200)),
                ('table_feature6', models.CharField(max_length=200)),
                ('table_feature7', models.CharField(max_length=200)),
                ('table_feature8', models.CharField(max_length=200)),
                ('table_feature9', models.CharField(max_length=200)),
                ('table_feature10', models.CharField(max_length=200)),
                ('table_price', models.IntegerField()),
                ('table_href', models.CharField(max_length=200)),
                ('pawnhost_section_title', models.CharField(max_length=200)),
                ('pawnhost_section_image', models.ImageField(upload_to='media/why_pawnhost')),
                ('pawnhost_section_h1', models.CharField(max_length=200)),
                ('pawnhost_section_p', models.CharField(max_length=200)),
                ('call_to_action_img', models.ImageField(upload_to='media/call_to_action')),
                ('call_to_action_title', models.CharField(max_length=200)),
                ('call_to_action_desc', models.TextField()),
                ('reviews_section_title', models.CharField(max_length=200)),
                ('review_image', models.ImageField(upload_to='media/reviews')),
                ('review_text', models.TextField()),
                ('review_credit', models.TextField()),
                ('transfer_website_title', models.CharField(max_length=200)),
                ('transfer_website_desc', models.TextField()),
                ('transger_website_href', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
