# Generated by Django 4.0.3 on 2022-03-15 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_homepage_feature_section_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='feature_section_card',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.call_to_action'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='reviews_section_card',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.review'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepage',
            name='feature_section_title',
            field=models.CharField(max_length=200),
        ),
    ]
