# Generated by Django 3.2.9 on 2022-03-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220308_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='call_to_action_img',
            field=models.ImageField(upload_to='call_to_action'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_image',
            field=models.ImageField(upload_to='hero'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='pawnhost_section_image',
            field=models.ImageField(upload_to='why_pawnhost'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='review_image',
            field=models.ImageField(upload_to='reviews'),
        ),
    ]
