# Generated by Django 4.0.3 on 2022-03-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_homepage_feature_section_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='feature_section_card',
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature_section_card',
            field=models.ManyToManyField(to='core.call_to_action'),
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='pricing_table',
        ),
        migrations.AddField(
            model_name='homepage',
            name='pricing_table',
            field=models.ManyToManyField(to='core.pricing_table'),
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='reviews_section_card',
        ),
        migrations.AddField(
            model_name='homepage',
            name='reviews_section_card',
            field=models.ManyToManyField(to='core.review'),
        ),
    ]
