# Generated by Django 3.2.9 on 2022-03-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220308_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='href_btn',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
