# Generated by Django 3.2.9 on 2022-03-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_homepage_about_p2'),
    ]

    operations = [
        migrations.CreateModel(
            name='pricing_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_title', models.CharField(max_length=200)),
                ('table_feature1', models.CharField(max_length=200)),
                ('table_feature2', models.CharField(max_length=200)),
                ('table_feature3', models.CharField(max_length=200)),
                ('table_feature4', models.CharField(max_length=200)),
                ('table_feature5', models.CharField(max_length=200)),
                ('table_feature6', models.CharField(max_length=200)),
                ('table_feature7', models.CharField(max_length=200)),
                ('table_feature8', models.CharField(max_length=200)),
                ('table_feature9', models.CharField(max_length=200)),
                ('table_feature10', models.CharField(max_length=200)),
                ('table_price', models.IntegerField()),
                ('table_href', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='table_feature1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='table_feature10',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='table_feature2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='table_feature3',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='table_feature4',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='table_feature5',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='table_feature6',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='table_feature7',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='table_feature8',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='table_feature9',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='table_href',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='table_price',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='table_title',
        ),
    ]
