# Generated by Django 3.2.9 on 2022-03-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220309_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='call_to_action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='call_to_action')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='reviews')),
                ('text', models.TextField()),
                ('credit', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='call_to_action_desc',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='call_to_action_img',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='call_to_action_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='review_credit',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='review_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='review_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='reviews_section_title',
        ),
    ]
