# Generated by Django 3.2.9 on 2022-03-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220309_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call_to_action',
            name='section_title',
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature_section_title',
            field=models.CharField(default='make a smart move today', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='reviews_section_title',
            field=models.CharField(default='What Do Others Say About PawnHost?', max_length=200),
            preserve_default=False,
        ),
    ]
