# Generated by Django 3.2.9 on 2022-03-09 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220309_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='section_title',
        ),
    ]
