# Generated by Django 3.2.9 on 2022-03-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_review_section_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='credit',
            field=models.CharField(max_length=200),
        ),
    ]
