# Generated by Django 3.2.9 on 2022-03-09 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_review_credit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='transger_website_href',
            new_name='transfer_website_href',
        ),
    ]
