# Generated by Django 3.2.9 on 2022-03-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_transger_website_href_homepage_transfer_website_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
