# Generated by Django 3.2.9 on 2022-03-09 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_review_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='active',
        ),
    ]
