# Generated by Django 3.2.9 on 2022-03-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_review_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='transfer_website_image',
            field=models.ImageField(default='', upload_to='transfer_website'),
            preserve_default=False,
        ),
    ]
