# Generated by Django 3.2.9 on 2022-03-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_homepage_transfer_website_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='page_desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='page_keywords',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='page_title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepage',
            name='why_pawnhost_p',
            field=models.TextField(),
        ),
    ]
